### PR TITLE
Create status page

### PR DESCRIPTION
**Pull request by MickinSahni**
Creating PR to create a new status page for Search.gov.

Includes 3 primary services: Admin Center, i14y, Search.gov API Search Endpoint

### CODE REVIEW

**Comment by MickinSahni** [comment]
@dawnpm the "i14y API" line specifically refers to the create, update, delete endpoints that are publicly available and utilized [by certain customers]. I did not explicitly create a line for the hosted results page so that's something we could add. 

Will that be part of your commit?

**Comment by dawnpm** [comment]
I ended up consolidating the different services in my commit, since the same error with the same suspected cause is popping up in various components of the overall service.

**Comment by MickinSahni** [comment]
@dawnpm I see you created a new post for the status page. Should we get rid of the one I created and keep yours?

**Comment by MickinSahni** [comment]
Also, I fixed the image path on your page so the icons show up. That's in the latest commit.

**Comment by dawnpm** [comment]
Let's chat in the morning, there were a couple commit process things I wasn't sure about.

**Comment by MickinSahni** [comment]
@dawnpm thoughts on this item? should I remove my post and merge?

**Comment by MickinSahni** [comment]
@dawnpm i'm going to remove my post

**Pull request merged**
