### PR TITLE
[#155836076] update search.gov sitemap

### PR DESCRIPTION
**Pull request by MothOnMars**
- add noindex robots tag to /tagged/ pages, allow crawling
- use jekyll-sitemap gem to generate sitemap
- disallow drafts folder in robots.txt
- remove old drafts
- update sample.md to prevent drafts from being indexed
- remove pinterest verification page
- use search.gov instead of www
- add pry

### CODE REVIEW

**Comment by MothOnMars** [comment]
@dawnpm , @noremmie can review the code changes, but I wanted you to take a look at the overall changes. I've removed the old drafts, and tweaked our robots.txt file to allow pages like `search.gov/tagged/foo` to be followed (so crawlers can find tagged posts), but not indexed. The new sitemap plugin also cleans up our urls so that, for example, `https://www.search.gov/manual/` is listed instead of `https://www.search.gov/manual/index.html`.

The final sitemap urls list, which is auto-generated, is as follows:
```
https://search.gov/
https://search.gov/blog/
https://search.gov/blog/adopting-hadoop.html
https://search.gov/blog/award-big-data.html
https://search.gov/blog/award-informationweek.html
https://search.gov/blog/cache.html
https://search.gov/blog/go-live.html
https://search.gov/blog/hadoop-bigger-ox.html
https://search.gov/blog/hadoop-rubyists.html
https://search.gov/blog/legacy-domains.html
https://search.gov/blog/open-source.html
https://search.gov/blog/power-users-recap.html
https://search.gov/blog/redesign.html
https://search.gov/blog/search-big-data.html
https://search.gov/blog/searchgov-blog.html
https://search.gov/blog/searchgov-faqs-indexing.html
https://search.gov/blog/seo-joe-pagano.html
https://search.gov/blog/serp-redesign-tips.html
https://search.gov/blog/serp-redesign.html
https://search.gov/customers.html
https://search.gov/developer/
https://search.gov/developer/govt-urls.html
https://search.gov/developer/govturls.html
https://search.gov/developer/i14y-testing.html
https://search.gov/developer/i14y.html
https://search.gov/developer/indexing-api.html
https://search.gov/developer/jobs.html
https://search.gov/developer/recalls.html
https://search.gov/feedback/feedback.html
https://search.gov/files/Article%20Links%20-%20Structuring%20Your%20Site%20for%20Better%20SEO%20Webinar.pdf
https://search.gov/files/GSA_%20VPAT_DigitalGovSearch.pdf
https://search.gov/files/Structuring%20Your%20Site%20Content%20for%20Better%20SEO%20Slides.pdf
https://search.gov/manual/
https://search.gov/manual/account.html
https://search.gov/manual/add-site.html
https://search.gov/manual/analytics-alerts.html
https://search.gov/manual/best-bets-graphics.html
https://search.gov/manual/best-bets.html
https://search.gov/manual/brand.html
https://search.gov/manual/clicks.html
https://search.gov/manual/clone-site.html
https://search.gov/manual/cname.html
https://search.gov/manual/code.html
https://search.gov/manual/collections.html
https://search.gov/manual/color-codes.html
https://search.gov/manual/content-overview.html
https://search.gov/manual/display-overview.html
https://search.gov/manual/domains-advanced.html
https://search.gov/manual/domains.html
https://search.gov/manual/drupal-7-module-instructions.html
https://search.gov/manual/drupal-8-module-instructions.html
https://search.gov/manual/drupal-module-troubleshooting.html
https://search.gov/manual/drupal.html
https://search.gov/manual/filter-content.html
https://search.gov/manual/filter-tags.html
https://search.gov/manual/flickr.html
https://search.gov/manual/govbox-federal-register.html
https://search.gov/manual/govbox-health.html
https://search.gov/manual/govbox-jobs.html
https://search.gov/manual/httpss-transition.html
https://search.gov/manual/i14y-drawers.html
https://search.gov/manual/instagram.html
https://search.gov/manual/module-codes.html
https://search.gov/manual/monthly-reports.html
https://search.gov/manual/no-results.html
https://search.gov/manual/preview.html
https://search.gov/manual/queries.html
https://search.gov/manual/referrers.html
https://search.gov/manual/routed-queries.html
https://search.gov/manual/rss.html
https://search.gov/manual/search-results-api.html
https://search.gov/manual/settings.html
https://search.gov/manual/site-overview.html
https://search.gov/manual/supported-languages.html
https://search.gov/manual/system-alert.html
https://search.gov/manual/third-party.html
https://search.gov/manual/training.html
https://search.gov/manual/twitter.html
https://search.gov/manual/typeahead-api.html
https://search.gov/manual/users.html
https://search.gov/manual/youtube.html
https://search.gov/pdf/2014-04-11-search-big-data.pdf
https://search.gov/pdf/seo-joe-pagano.pdf
https://search.gov/quote/agriculture.html
https://search.gov/quote/bia.html
https://search.gov/quote/commerce.html
https://search.gov/quote/defense.html
https://search.gov/quote/dhs.html
https://search.gov/quote/education.html
https://search.gov/quote/ers.html
https://search.gov/quote/gartner.html
https://search.gov/quote/labor.html
https://search.gov/quote/sec.html
https://search.gov/quote/white-house.html
https://search.gov/releases/april-2012.html
https://search.gov/releases/april-2013.html
https://search.gov/releases/april-2014.html
https://search.gov/releases/april-2017.html
https://search.gov/releases/august-2011.html
https://search.gov/releases/august-2012.html
https://search.gov/releases/august-2013.html
https://search.gov/releases/august-2014.html
https://search.gov/releases/august-2017.html
https://search.gov/releases/december-2011.html
https://search.gov/releases/december-2012.html
https://search.gov/releases/december-2013.html
https://search.gov/releases/december-2016.html
https://search.gov/releases/december-2017.html
https://search.gov/releases/february-2012.html
https://search.gov/releases/february-2013.html
https://search.gov/releases/february-2014.html
https://search.gov/releases/february-2017.html
https://search.gov/releases/january-2012.html
https://search.gov/releases/january-2013.html
https://search.gov/releases/january-2014.html
https://search.gov/releases/january-2017.html
https://search.gov/releases/january-2018.html
https://search.gov/releases/july-2011.html
https://search.gov/releases/july-2012.html
https://search.gov/releases/july-2013.html
https://search.gov/releases/july-2014.html
https://search.gov/releases/july-2017.html
https://search.gov/releases/june-2011.html
https://search.gov/releases/june-2012.html
https://search.gov/releases/june-2013.html
https://search.gov/releases/june-2014.html
https://search.gov/releases/june-2017.html
https://search.gov/releases/march-2012.html
https://search.gov/releases/march-2013.html
https://search.gov/releases/march-2014.html
https://search.gov/releases/march-2017.html
https://search.gov/releases/may-2011.html
https://search.gov/releases/may-2012.html
https://search.gov/releases/may-2013.html
https://search.gov/releases/may-2014.html
https://search.gov/releases/may-2017.html
https://search.gov/releases/november-2011.html
https://search.gov/releases/november-2012.html
https://search.gov/releases/november-2013.html
https://search.gov/releases/november-2016.html
https://search.gov/releases/november-2017.html
https://search.gov/releases/october-2011.html
https://search.gov/releases/october-2012.html
https://search.gov/releases/october-2013.html
https://search.gov/releases/october-2014.html
https://search.gov/releases/october-2017.html
https://search.gov/releases/september-2011.html
https://search.gov/releases/september-2012.html
https://search.gov/releases/september-2013.html
https://search.gov/releases/september-2014.html
https://search.gov/releases/september-2017.html
https://search.gov/tos.html
```

**Comment by noremmie** [comment]
The code changes LGTM 👍 And I'm assuming that @dawnpm will chime in if any of those deleted pages should not actually be deleted.

**Comment by dawnpm** [comment]
All these removals are green lit.

**Comment by noremmie** [comment]
👍 for 3a9cada22ebdaa8d84f82c9e505c09462b6cb7e3 too

**Comment by dawnpm** [comment]
@MothOnMars how did https://search.gov/manual/httpss-transition.html get that extra `s`? the live file's url is correct: https://search.gov/manual/https-transition.html

And please forgive an uninformed question - if the sitemap is automatically generated, why does it need fixing?

**Comment by MothOnMars** [comment]
I think that extra "s" was a typo from when I was pulling the urls from the updated sitemap. I see 'https-transition.html' in the actual generated sitemap.

As for "why does it need fixing?", that is a valid question. I will add more info to the PT story on what is being updated and why (which I really should have done the first time around...).

**Pull request merged**
